---
- name: apache install
  package:
    name: httpd
    state: latest

- name: start and enable apache
  systemd:
    name: httpd
    state: started
    enabled: yes

- name: restart apache
  notify: restart-apache
